#!/usr/bin/env bun
/**
 * Generate `src/generated/embedded-assets.js` (+ `.d.ts`), the manifest of
 * files baked into the standalone binary via `bun build --compile`.
 *
 * Bun only embeds files reached through a static `import … with { type: "file" }`,
 * so this script emits one such import per asset and a logical-path → file-path
 * map. The import result is a real disk path in dev (so the app reads live files)
 * and a `/$bunfs/…` path in the compiled binary — one code path for both.
 *
 * Re-run whenever assets are ADDED or REMOVED (content changes need no re-gen;
 * the map points at the live file in dev). Wired into `bun run build`.
 *
 *   bun run scripts/gen-assets.ts
 */
import { readdirSync, statSync, mkdirSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const REPO = resolve(import.meta.dir, "..");
const GEN_DIR = join(REPO, "src", "generated");

interface Asset {
  logical: string; // e.g. "prompts/greg.md", "public/zen-orbs-3d.js"
  importPath: string; // relative to src/generated/, e.g. "../../prompts/greg.md"
}

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.isFile()) out.push(full);
  }
  return out;
}

const assets: Asset[] = [];

// prompts/*.md — runtime prompt templates (skip repo docs).
for (const f of walk(join(REPO, "prompts"))) {
  const name = relative(join(REPO, "prompts"), f).split("\\").join("/");
  if (!name.endsWith(".md") || name === "CLAUDE.md") continue;
  assets.push({ logical: `prompts/${name}`, importPath: `../../prompts/${name}` });
}

// config/*.json — default config snapshots seeded into the data dir on first run.
for (const f of walk(join(REPO, "config"))) {
  const name = relative(join(REPO, "config"), f).split("\\").join("/");
  if (!name.endsWith(".json")) continue;
  assets.push({ logical: `config/${name}`, importPath: `../../config/${name}` });
}

// src/html/public/** — static web assets. Skip .gitkeep and user-uploaded
// wallpapers (public/wallpapers/*), but keep the shipped defaults.
const PUBLIC = join(REPO, "src", "html", "public");
for (const f of walk(PUBLIC)) {
  const rel = relative(PUBLIC, f).split("\\").join("/");
  const base = rel.split("/").pop() ?? "";
  if (base === ".gitkeep") continue;
  if (rel.startsWith("wallpapers/") && !rel.startsWith("wallpapers/defaults/")) continue;
  assets.push({ logical: `public/${rel}`, importPath: `../html/public/${rel}` });
}

// src/db/**/*.sql — schema files + numbered migrations, read at DB init.
const DB = join(REPO, "src", "db");
for (const f of walk(DB)) {
  const rel = relative(DB, f).split("\\").join("/");
  if (!rel.endsWith(".sql")) continue;
  assets.push({ logical: `db/${rel}`, importPath: `../db/${rel}` });
}

assets.sort((a, b) => a.logical.localeCompare(b.logical));

const imports = assets
  .map((a, i) => `import a${i} from ${JSON.stringify(a.importPath)} with { type: "file" };`)
  .join("\n");
const entries = assets
  .map((a, i) => `  ${JSON.stringify(a.logical)}: a${i},`)
  .join("\n");

const js = `// @ts-nocheck
// AUTO-GENERATED by scripts/gen-assets.ts — do not edit.
// Maps a logical asset path to its on-disk (dev) or /$bunfs (compiled) file path.
${imports}

export const EMBEDDED_ASSETS = {
${entries}
};
`;

const dts = `// AUTO-GENERATED by scripts/gen-assets.ts — do not edit.
export declare const EMBEDDED_ASSETS: Record<string, string>;
`;

mkdirSync(GEN_DIR, { recursive: true });
writeFileSync(join(GEN_DIR, "embedded-assets.js"), js);
writeFileSync(join(GEN_DIR, "embedded-assets.d.ts"), dts);

console.log(`gen-assets: embedded ${assets.length} assets → src/generated/embedded-assets.js`);
for (const a of assets) console.log(`  ${a.logical}`);
