import { readFileSync } from "node:fs";
import { EMBEDDED_ASSETS } from "./generated/embedded-assets";

/**
 * Access layer over assets baked into the binary (`bun build --compile`).
 *
 * `EMBEDDED_ASSETS` (generated by `scripts/gen-assets.ts`) maps a logical path
 * like `"prompts/greg.md"` or `"public/zen-orbs-3d.js"` to a file path that
 * resolves to the real source file in dev and a `/$bunfs/…` path in the compiled
 * binary. `node:fs` and `Bun.file` both work against either, so one code path
 * serves dev and packaged runs. See `scripts/gen-assets.ts` for the embed rules.
 */

/**
 * True when running as a compiled standalone binary. `Bun.embeddedFiles` is
 * populated only by `--compile`; it is an empty array under `bun run`. Used to
 * decide whether mutable config lives in the repo (dev) or the data dir (binary).
 */
export function isCompiledBinary(): boolean {
  return typeof Bun !== "undefined" && Array.isArray(Bun.embeddedFiles) && Bun.embeddedFiles.length > 0;
}

export function hasAsset(logical: string): boolean {
  return Object.prototype.hasOwnProperty.call(EMBEDDED_ASSETS, logical);
}

/** Resolved fs path for an embedded asset, or null if not embedded. */
export function assetFsPath(logical: string): string | null {
  return hasAsset(logical) ? EMBEDDED_ASSETS[logical]! : null;
}

/** A `BunFile` for an embedded asset (streamable static response), or null. */
export function assetFile(logical: string): ReturnType<typeof Bun.file> | null {
  const p = EMBEDDED_ASSETS[logical];
  return p ? Bun.file(p) : null;
}

/** Synchronous UTF-8 read — safe for module-load-time prompt/config loads. */
export function assetTextSync(logical: string): string {
  const p = EMBEDDED_ASSETS[logical];
  if (!p) throw new Error(`embedded asset not found: ${logical}`);
  return readFileSync(p, "utf-8");
}

/** Synchronous raw read — used to seed mutable config into the data dir. */
export function assetBytesSync(logical: string): Buffer {
  const p = EMBEDDED_ASSETS[logical];
  if (!p) throw new Error(`embedded asset not found: ${logical}`);
  return readFileSync(p);
}

/** Logical paths under a prefix, e.g. `listAssets("public/wallpapers/defaults/")`. */
export function listAssets(prefix: string): string[] {
  return Object.keys(EMBEDDED_ASSETS)
    .filter((k) => k.startsWith(prefix))
    .sort();
}
